# Site
name: "Laith Yousif"
title: "Laith Yousif"
description: "Blog for basic level blabbing"
logo: 'assets/images/logo_tr.png'
favicon: 'assets/images/logo_tr.png'
baseurl: 
google_analytics: 
mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Laith Yousif
    display_name: Laith
    gravatar: 4dd659f80f52923c8df63837d5b19ff0
    email: Laith@blabby.me
    web: https://www.laithyousif.com
    twitter: https://twitter.com/lnyousif
    description: "Baghdad born techie, Aspiring Writer, and Comic
ليبرالي علماني. كاتب وكوميدي"


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
